services:
  web:
    build: .
    command: python backend/server/manage.py runserver 0.0.0.0:8000
    ports:
      - ${dbPort}
    depends_on:
      - db
    volumes:
      - '.:/app:rw'
      - './data:/data:rw'

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${dbName}
      - POSTGRES_USER=${dbUser}
      - POSTGRES_PASSWORD=${dbPw}
  volumes:
    - postgres_data:
      - /var/lib/postgresql/data
