# Generated by Django 5.1.3 on 2024-11-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0004_delete_testusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userID',
            field=models.AutoField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
