# Generated by Django 5.1.3 on 2024-11-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0006_alter_customuser_email_alter_customuser_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
