# Generated by Django 5.1.3 on 2024-11-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0007_alter_customuser_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
