# Generated by Django 5.1.3 on 2024-11-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0003_plaiditem'),
        ('restfulapi', '0008_alter_customuser_userid'),
    ]

    operations = [
    ]
